### PR TITLE
Budgets implementation

### LINKED ISSUE #65: Budgets
As a normal user, I make some Budgets by each category monthly, I want to track the progress of my expenses with the expected amount of money that I want to use this month.

### PR DESCRIPTION
**Pull request by AndresMorelos**
Fix #65

## TODO

- [x] Add modifications to user model to support budgets.
- [x] Add the form to register a new budget
- [x] Update the budget use each time that a payment is accepted
- [x] Notify the user when the budget is 100% used (UI notification by this moment)

### CODE REVIEW

**Comment by AndresMorelos** [comment]
URL utils: 

- http://storybook.emeraldui.com/?path=/story/progressbar--controlled 
- http://docs.emeraldui.com/Progressbar

**Comment by AndresMorelos** [comment]
## Screen Shots 

### UI Notification

image

**Comment by AndresMorelos** [comment]
@FlavioAandres @FlavioAPareja Take a look on this.

**Review by FlavioAandres — APPROVED** [review]
Nice

**Pull request merged**
