### PR TITLE
New user tab

### PR DESCRIPTION
**Pull request by FlavioAandres**

### CODE REVIEW

**Comment by FlavioAandres** [comment]
# To get your current categories created in `payments` collection

```
db.getCollection('payments').aggregate([{$group: {_id:"$category"}}, {$project: {
  value: "$_id",
  label: "",
  _id: 0,
}} ]).toArray()
```

**Comment by FlavioAandres** [comment]
## Views: 

image
image

**Comment by FlavioAandres** [comment]
@AndresMorelos please check this pr: 

I've created two new routes: 
-  GET /user
- POST /user/categories 

before to deploy create your categories directly in the user schema, using the query in the previous comment 🤘🏼

**Comment by AndresMorelos** [comment]
@FlavioAandres LGTM

**Pull request merged**
