### PR TITLE
Telegram bot

### LINKED ISSUE #50: Move Chatbot to Telegram
There is no description, title is enought 🦊

### PR DESCRIPTION
**Pull request by AndresMorelos**
Will fix #50 

First Merge #51 

## ScreenShots
image

### CODE REVIEW

**Comment by AndresMorelos** [comment]
@FlavioAandres @FlavioAPareja Take a look on this one.

**Comment by FlavioAandres** [comment]
<3 Please hold this PR until I deploy my changes! Thanks a lot for this

**Comment by FlavioAandres** [comment]
@AndresMorelos I'm Ready to merge this, just let me know how to configure the bot with telegram :th

**Comment by AndresMorelos** [comment]
@FlavioAandres @FlavioAPareja 

1. I will add a guide soon, but you will need to know the BotFather (https://www.sitepoint.com/how-to-build-your-first-telegram-chatbot-with-node-js/)
2. Yes, you will need to update the current ones to Expense type (This was a feature of the already merge PR, I just created a new PR from that branch before merge the PR)
3. Yes, the User Schema will add a new setting, the Chat Id, but that will be automatically made by the bot so don't worry about.


## Update

Now this branch/PR has the latest changes of master.

**Comment by AndresMorelos** [comment]
@FlavioAandres @FlavioAPareja This PR is done `Add` Command finished

**Pull request merged**
